name: CI workflow 

on:
  workflow_dispatch:


jobs:
  ci-build-jobs:
    runs-on: self-hosted
    
    steps:
      - name: checkout todo code
        run: echo "Checking out code..."

      - name: run ci build jobs
        run: |
          echo `Running CI build jobs...`
          echo `Build job completed at $(date)`